### PR TITLE
Add support for Laravel 5.8

### PR DESCRIPTION
**Pull request by snellingio**
Add support for 5.7, 5.8

### CODE REVIEW

**Comment by scramatte** [comment]
Hello

Can you please merge patch  to be able to use it with laravel 5.7 and 5.8
Regards

**Comment by gizburdt** [comment]
+1

I emailed some people to ask who is responsible for this package, but I didn't get a response.

Would be awesome if the PR's could get merged.

**Comment by oliverbj** [comment]
Could this be merged?

**Comment by atymic** [comment]
Closed in favour of #27

**Pull request closed without merging**
