### PR TITLE
Updated Laravel dependencies to 5.6

### PR DESCRIPTION
**Pull request by robinvdvleuten**
Hi there! I've updated the dependencies to be compatible with the Laravel 5.6 upgrade.

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
@mpociot would you mind looking at this PR? Its now a couple of weeks ago since 5.6 is released.

**Comment by devinhyden** [comment]
Any change this could be updated to 5.6?

**Comment by jamesgraham** [comment]
Also would appreciate a merge 🙏

**Comment by jradtilbrook** [comment]
I'd also like this merged. Is this package now unmaintained?

**Comment by jradtilbrook** [comment]
What is the risk of just using 5.* so we don’t have to keep doing this? I’d hope this API wouldn’t change between minor versions right? This library has blocked me upgrading twice now and I don’t really want it a third time

**Comment by mpociot** [comment]
Sorry for not looking at this earlier.

**Comment by robinvdvleuten** [comment]
@mpociot no problem! Thanks for merging ✌️

**Pull request merged**
