### PR TITLE
Added Notification to routeNotificationFor method

### PR DESCRIPTION
**Pull request by SebastiaanKloos**
Added the Notification class to the routeNotificationFor method. I need to get the notification so  I can return the webhook url based on the type of notification like so:

```php
public function routeNotificationForWebhook($notification)
{
    if ($notification instanceof IssueStatusUpdatedNotification) {
        return $this->issue_custom_webhook;
    }

    return $this->custom_webhook;
}
```

It's the same as how it works with the Slack channel.

Thanks in advance for your time!

### CODE REVIEW

**Comment by V35CH** [comment]
Will this PR be merged in the feature?
I need the possibility to set the url based on the notification and not on the notifiable.

**Comment by ricsands2801** [comment]
+1 for this

**Comment by freekmurze** [comment]
Because...
- this change seems correct
- a lot of people seem to want it
- we need it as well for a project
- this project seems not actively maintained

... I've decided to step in merge this and tag a release that contains these changes.

**Comment by SebastiaanKloos** [comment]
Thank you @freekmurze. Really appreciate it 🙏

**Comment by ricsands2801** [comment]
Thanks @freekmurze!

**Pull request merged**
